test = User.create!(name: 'qin', password: "test", password_confirmation: "test", email: "self@test.com")
lois = User.create!(name: 'lois', password: "test", password_confirmation: "test", email: "lois@test.com")
Practice.create(name: "learning about the virtue of patience", category: "live", creator_id:1)
Practice.create(name: "learning about the virtue of truthfulness", category: "live", creator_id:1)
Practice.create(name: "learning about the virtue of integrity", category: "live", creator_id:1)
Practice.create(name: "learning about the virtue of justice", category: "live", creator_id:1)
Practice.create(name: "learning about the virtue of prudence", category: "live", creator_id:2)
Practice.create(name: "learning about the virtue of temperance", category: "live", creator_id:2)
Practice.create(name: "learning about the virtue of humour", category: "live", creator_id:2)
Practice.create(name: "learning about the virtue of diligence", category: "live", creator_id:2)
Practice.create(name: "learning about the virtue of misericordia", category: "live", creator_id:2)
Practice.create(name: "learning about the virtue of humility", category: "live", creator_id:2)
Practice.create(name: "learning about the virtue of loyalty", category: "live", creator_id:1)
Practice.create(name: "learning about the virtue of courtesy", category: "live", creator_id:1)
Practice.create(name: "learning about the virtue of courage", category: "live", creator_id:1)
Practice.create(name: "learning about the virtue of unselfishness", category: "live", creator_id:1)
Practice.create(name: "learning about the virtue of benevolence", category: "live", creator_id:1)
Practice.create(name: "learning about the virtue of silence", category: "live", creator_id:1)
Practice.create(name: "learning about the virtue of frugality", category: "live", creator_id:1)
Practice.create(name: "learning about the virtue of magnanity", category: "live", creator_id:1)
Practice.create(name: "learning about the virtue of intellectual humility", category: "live", creator_id:1)
Practice.create(name: "learning about the virtue of intellectual thoroughness", category: "live", creator_id:1)
Practice.create(name: "learning about the virtue of open-mindedness", category: "live", creator_id:1)
Practice.create(name: "learning about the virtue of fair-mindedness", category: "live", creator_id:1)



Practice.create(name: "spending time on things that contribute to my well-being and growth", category: "love myself", creator_id:1)
Practice.create(name: "taking care of my body", category: "love myself",creator_id:2)
Practice.create(name: "not spending any money on non-essentials", category: "love myself",creator_id:1)
Practice.create(name: "tidying my room after each day", category: "love myself",creator_id:1)
Practice.create(name: "stretching to better take care of my body", category: "love myself",creator_id:2)
Practice.create(name: "not spending time unintentionally and mindlessly on social media", category: "love myself",creator_id:1)
Practice.create(name: "upholding my promise to myself to not to engage in self-defeating behavior", category: "love myself",creator_id:1)

Practice.create(name: "active, attentive, compassionate listening", category: "love my family, friends and neighbours",creator_id:1)
Practice.create(name: "refraining from gossip or any talk that doesn't uplift another", category: "love my family, friends and neighbours",creator_id:1)
Practice.create(name: "offering to pick up the chores or just picking them up", category: "love my family, friends and neighbours",creator_id:1)
Practice.create(name: "asking for clarification and taking a level-headed approach when emotions heighten in a disagreement", category: "love my family, friends and neighbours",creator_id:1)
Practice.create(name: "praying for the other's healing", category: "love my family, friends and neighbours",creator_id:2)

Practice.create(name: "remembering that the other also has a story, struggles and may be severely wounded", category: "love my enemies",creator_id:1)
Practice.create(name: "praying for the other's healing", category: "love my enemies",creator_id:1)
Practice.create(name: "remembering the mercies offered to me and forgiving others for their offences", category: "love my enemies",creator_id:1)
Practice.create(name: "remembering that i am a sinner and that the other just has a different sin than me", category: "love my enemies",creator_id:1)
Practice.create(name: "learning to see the other with eyes of mercy and compassion", category: "love my enemies",creator_id:1)
Practice.create(name: "asking for clarification and taking a level-headed approach when emotions heighten in a disagreement", category: "love my enemies",creator_id:1)
Practice.create(name: "attentive listening to others especially when they say something i don't agree with, asking them to clarify and share how they've come to their views and respectfully disengaging should conversation become personally hostile", category: "love my enemies",creator_id:1)

Practice.create(name: "reducing my meat intake / not eating any meat", category: "care for creation and our common home",creator_id:2)
Practice.create(name: "eating more veggies and legumes instead of meat", category: "care for creation and our common home",creator_id:1)
Practice.create(name: "reducing waste and plastic usage by bringing own container and silverware / chopsticks", category: "care for creation and our common home",creator_id:1)
Practice.create(name: "being aware that everything is a gift and i am called to be a steward", category: "care for creation and our common home",creator_id:1)
